module.exports = {
  roots: ['<rootDir>/src', '<rootDir>/test'],
  testMatch: [
    '**/__tests__/**/*.+(ts|tsx|js)',
    '**/?(*.)+(spec|test).+(ts|tsx|js)',
  ],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '\\.[jt]sx?$': 'babel-jest',
  },
  moduleNameMapper: {
    '@solana/web3.js': '@solana/web3.js',
    '../lib/raydium/util/web3.js': '../lib/raydium/util/web3.ts',
    './util/web3.js': './util/web3.ts',
    './web3.js': './web3.ts',
    '../lib/constants.js': '../lib/constants.ts',
    '../constants.js': '../constants.ts',
    './constants.js': './constants.ts',
    '../lib/raydium/util/layout.js': '../lib/raydium/util/layout.ts',
    '../marshmellow/index.js': '../marshmellow/index.ts',
    './buffer-layout.js': './buffer-layout.ts',
    '../lib/raydium/createAmm.js': '../lib/raydium/createAmm.ts',
    './util/errors.js': './util/errors.ts',
    '../lib/raydium/util/ids.js': '../lib/raydium/util/ids.ts',
    './util/ids.js': './util/ids.ts',
    './ids.js': './ids.ts',
    '../lib/util.js': '../lib/util.ts',
    '../util.js': '../util.ts',
    './util/layouts.js': './util/layouts.ts',
    './layouts.js': './layouts.ts',
    '../lib/raydium/util/tokens.js': '../lib/raydium/util/tokens.ts',
    './util/tokens.js': './util/tokens.ts',
    './tokens.js': './tokens.ts',
    '../lib/raydium/util/swap.js': '../lib/raydium/util/swap.ts',
    './util/swap.js': './util/swap.ts',
    '../lib/raydium/util/safe-math.js': '../lib/raydium/util/safe-math.ts',
    './safe-math.js': './safe-math.ts',
    '../lib/raydium/util/liquidity.js': '../lib/raydium/util/liquidity.ts',
    '../lib/serum/serum.js': '../lib/serum/serum.ts',
    '../lib/fee.js': '../lib/fee.ts',
    './fee.js': './fee.ts',
    '../lib/raydium/util/poolKeys.js': '../lib/raydium/util/poolKeys.ts',
  },
  transformIgnorePatterns: ['/node_modules/(?!lodash-es)'],
}
